[functions.stripe-webhook]
verify_jwt = false

[functions.notificar-cuestionario]
verify_jwt = false

[functions.crear-suscripcion]
verify_jwt = true

[functions.crear-checkout-suscripcion]
verify_jwt = true

[functions.generar-protocolo-rehab]
verify_jwt = true

[functions.generar-suplementacion]
verify_jwt = true

[functions.enviar-mensajes-programados]
verify_jwt = false

[functions.analizar-cliente-mensual]
verify_jwt = false
