export const BIBLIOTECA_EJERCICIOS = [
  {
    nombre: "Press de banca con barra",
    patron: "empuje_horizontal",
    grupo: "Pecho",
    grupo2: "Tríceps,Hombros",
    nivel: "intermedio",
    tipo: "fuerza",
    modalidades: "fuerza,hipertrofia,hibrido",
    tecnica: "Agarre ligeramente más ancho que los hombros. Escápulas retraídas y deprimidas. Baja la barra hasta el pecho tocando levemente. Empuja en trayectoria ligeramente diagonal. Codos a 45-75 grados del torso.",
    yt_id: "rT7DgCr-3pg",
    sinonimos: "bench press,press banca,press banca barra",
  },
  {
    nombre: "Press de banca con mancuernas",
    patron: "empuje_horizontal",
    grupo: "Pecho",
    grupo2: "Tríceps,Hombros",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "fuerza,hipertrofia,perdida_grasa",
    tecnica: "Mayor rango de movimiento que con barra. Baja hasta que los codos queden a 90 grados. Junta las mancuernas en la parte superior sin que se toquen. Control total en la bajada.",
    yt_id: "VmB1G1K7v94",
    sinonimos: "press mancuernas,dumbbell press",
  },
  {
    nombre: "Press inclinado con barra",
    patron: "empuje_horizontal",
    grupo: "Pecho",
    grupo2: "Hombros",
    nivel: "intermedio",
    tipo: "fuerza",
    modalidades: "fuerza,hipertrofia",
    tecnica: "Banco a 30-45 grados. Agarre ligeramente más estrecho que el press plano. Enfoca el pecho superior. Codos a 45 grados del cuerpo.",
    yt_id: "jPLdzuHckI8",
    sinonimos: "press inclinado,incline press,press inclinado barra",
  },
  {
    nombre: "Aperturas con mancuernas",
    patron: "empuje_horizontal",
    grupo: "Pecho",
    grupo2: "",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "hipertrofia",
    tecnica: "Codos ligeramente flexionados durante todo el movimiento. Baja hasta sentir estiramiento en el pecho. Junta las mancuernas describiendo un arco. No extiendas completamente los codos.",
    yt_id: "eozdVDA78K0",
    sinonimos: "aperturas,flies,flyes,chest fly",
  },
  {
    nombre: "Fondos en paralelas",
    patron: "empuje_vertical",
    grupo: "Pecho",
    grupo2: "Tríceps",
    nivel: "intermedio",
    tipo: "peso_corporal",
    modalidades: "calistenia,fuerza,hipertrofia",
    tecnica: "Inclínate hacia adelante para enfatizar el pecho. Baja hasta que los hombros estén a la altura de los codos. Control total en la fase excéntrica. Si es para tríceps, mantén el torso vertical.",
    yt_id: "2z8JmcrW-As",
    sinonimos: "fondos paralelas,dips,parallel bar dips",
  },
  {
    nombre: "Flexiones",
    patron: "empuje_horizontal",
    grupo: "Pecho",
    grupo2: "Tríceps,Hombros",
    nivel: "principiante",
    tipo: "peso_corporal",
    modalidades: "calistenia,wellness,perdida_grasa",
    tecnica: "Cuerpo recto de cabeza a talones. Manos a la anchura de los hombros o más. Baja el pecho hasta casi tocar el suelo. Codos a 45 grados del cuerpo.",
    yt_id: "IODxDxX7oi4",
    sinonimos: "push ups,pushups,lagartijas",
  },
  {
    nombre: "Dominadas",
    patron: "tiron_vertical",
    grupo: "Espalda",
    grupo2: "Bíceps",
    nivel: "avanzado",
    tipo: "peso_corporal",
    modalidades: "calistenia,fuerza,hipertrofia",
    tecnica: "Agarre pronado más ancho que hombros. Inicia el movimiento deprimiendo las escápulas. Lleva el pecho a la barra. Control total en la bajada. Cuelga completamente al final.",
    yt_id: "eGo4IYlbE5g",
    sinonimos: "pull ups,chin ups,dominadas barra",
  },
  {
    nombre: "Jalón al pecho en polea",
    patron: "tiron_vertical",
    grupo: "Espalda",
    grupo2: "Bíceps",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "fuerza,hipertrofia,perdida_grasa",
    tecnica: "Agarre más ancho que hombros. Inclínate ligeramente hacia atrás. Lleva la barra al pecho superior. Aprieta la espalda al final del movimiento. Control en la subida.",
    yt_id: "CAwf7n6Luuc",
    sinonimos: "jalon,lat pulldown,jalón polea",
  },
  {
    nombre: "Jalón con agarre neutro",
    patron: "tiron_vertical",
    grupo: "Espalda",
    grupo2: "Bíceps",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "fuerza,hipertrofia",
    tecnica: "Agarre neutro con manos enfrentadas. Codos pegados al cuerpo durante el descenso. Mayor activación del dorsal que con agarre prono. Ideal para principiantes.",
    yt_id: "6kALZjUUd4E",
    sinonimos: "jalon neutro,jalon agarre neutro",
  },
  {
    nombre: "Remo con barra",
    patron: "tiron_horizontal",
    grupo: "Espalda",
    grupo2: "Bíceps,Trapecios",
    nivel: "intermedio",
    tipo: "fuerza",
    modalidades: "fuerza,hipertrofia",
    tecnica: "Espalda casi paralela al suelo. Agarre pronado a la anchura de hombros. Lleva la barra al ombligo o abdomen bajo. Codos pegados al cuerpo. Aprieta la espalda en la contracción.",
    yt_id: "G8l_8chR5BE",
    sinonimos: "barbell row,remo barra,bent over row",
  },
  {
    nombre: "Remo con mancuerna",
    patron: "tiron_horizontal",
    grupo: "Espalda",
    grupo2: "Bíceps",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "fuerza,hipertrofia,perdida_grasa",
    tecnica: "Apoya la rodilla y mano en el banco. Espalda paralela al suelo. Lleva la mancuerna al costado del abdomen. Codo pegado al cuerpo. Rotación suave del torso al final.",
    yt_id: "pYcpY20QaE8",
    sinonimos: "dumbbell row,remo mancuerna,one arm row",
  },
  {
    nombre: "Remo en polea baja",
    patron: "tiron_horizontal",
    grupo: "Espalda",
    grupo2: "Bíceps",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "fuerza,hipertrofia,perdida_grasa",
    tecnica: "Espalda erguida durante todo el movimiento. Lleva el agarre al abdomen. Codos pegados al cuerpo. Aprieta las escápulas al final. No balancees el torso.",
    yt_id: "GZbfZ033f74",
    sinonimos: "cable row,polea baja,seated row",
  },
  {
    nombre: "Face pull",
    patron: "tiron_horizontal",
    grupo: "Hombros",
    grupo2: "Trapecios,Manguito",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "fuerza,hipertrofia,wellness",
    tecnica: "Polea a altura de cara. Agarre con cuerdas. Lleva las manos a los lados de la cara. Codos a la altura de los hombros. Gira externamente los hombros. Excelente para salud del hombro.",
    yt_id: "rep-qVOkqgk",
    sinonimos: "face pull polea,face pulls",
  },
  {
    nombre: "Press militar con barra",
    patron: "empuje_vertical",
    grupo: "Hombros",
    grupo2: "Tríceps",
    nivel: "intermedio",
    tipo: "fuerza",
    modalidades: "fuerza,hipertrofia,potencia",
    tecnica: "De pie o sentado. Agarre a la anchura de hombros. Barra a la altura del mentón. Empuja verticalmente. Core activado. No arquees la espalda baja.",
    yt_id: "2yjwXTZQDDI",
    sinonimos: "overhead press,press militar,OHP,press hombros",
  },
  {
    nombre: "Press de hombros con mancuernas",
    patron: "empuje_vertical",
    grupo: "Hombros",
    grupo2: "Tríceps",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "fuerza,hipertrofia,perdida_grasa",
    tecnica: "Sentado o de pie. Mancuernas a la altura de los hombros. Sube hasta casi extender los codos. Baja con control. No bloquees los codos arriba.",
    yt_id: "qEwKCR5JCog",
    sinonimos: "dumbbell shoulder press,press mancuernas hombros",
  },
  {
    nombre: "Elevaciones laterales",
    patron: "aislamiento",
    grupo: "Hombros",
    grupo2: "",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "hipertrofia,fuerza",
    tecnica: "Codos ligeramente flexionados. Sube hasta que los brazos queden paralelos al suelo. Meñique ligeramente elevado. No balancees el cuerpo. Fase excéntrica de 3 segundos.",
    yt_id: "3VcKaXpzqRo",
    sinonimos: "lateral raises,elevaciones laterales mancuernas",
  },
  {
    nombre: "Elevaciones frontales",
    patron: "aislamiento",
    grupo: "Hombros",
    grupo2: "",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "hipertrofia",
    tecnica: "Sube hasta la altura de los ojos. Agarre neutro o prono. Codos ligeramente flexionados. No balancees. Ideal para hombro anterior.",
    yt_id: "hRjqozvBBa4",
    sinonimos: "front raises,elevaciones frontales",
  },
  {
    nombre: "Curl de bíceps con barra",
    patron: "aislamiento",
    grupo: "Bíceps",
    grupo2: "",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "hipertrofia,fuerza",
    tecnica: "Codos fijos a los costados. Supinación completa al subir. Baja completamente. No balancees el cuerpo. Pausa de 1 segundo arriba.",
    yt_id: "ykJmrZ5v0Oo",
    sinonimos: "bicep curl barra,barbell curl,curl biceps",
  },
  {
    nombre: "Curl de bíceps con mancuernas",
    patron: "aislamiento",
    grupo: "Bíceps",
    grupo2: "",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "hipertrofia,fuerza,perdida_grasa",
    tecnica: "Alterna o simultáneo. Supina la muñeca al subir. Codo fijo. Baja completamente extendiendo el brazo. Mayor rango que con barra.",
    yt_id: "sAq_ocpRh_I",
    sinonimos: "dumbbell curl,curl mancuernas",
  },
  {
    nombre: "Curl martillo",
    patron: "aislamiento",
    grupo: "Bíceps",
    grupo2: "Braquial",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "hipertrofia",
    tecnica: "Agarre neutro durante todo el movimiento. Trabaja el braquial y braquiorradial más que el bíceps. Codo fijo al costado. Sube hasta 90 grados.",
    yt_id: "TwD-YGVP4Bk",
    sinonimos: "hammer curl,curl martillo mancuernas",
  },
  {
    nombre: "Extensión de tríceps en polea",
    patron: "aislamiento",
    grupo: "Tríceps",
    grupo2: "",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "hipertrofia,fuerza,perdida_grasa",
    tecnica: "Codos fijos a los costados. Extiende completamente. Agarre prono o neutro. No abras los codos. Ideal para aislar las tres cabezas.",
    yt_id: "2-LAMcpzODU",
    sinonimos: "tricep pushdown,polea tríceps,cable tricep",
  },
  {
    nombre: "Press francés",
    patron: "aislamiento",
    grupo: "Tríceps",
    grupo2: "",
    nivel: "intermedio",
    tipo: "fuerza",
    modalidades: "hipertrofia",
    tecnica: "Tumbado. Baja la barra o mancuernas hacia la frente. Codos apuntando al techo. Extiende completamente. No muevas los codos de su posición.",
    yt_id: "d_KZxkY_0cM",
    sinonimos: "skull crusher,french press,rompecráneos",
  },
  {
    nombre: "Extensión de tríceps sobre la cabeza",
    patron: "aislamiento",
    grupo: "Tríceps",
    grupo2: "",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "hipertrofia",
    tecnica: "Cabeza larga del tríceps más activada. Mancuerna o barra sobre la cabeza. Codos apuntando al frente. Baja hasta detrás de la cabeza.",
    yt_id: "YbX7Wd8jQ-Q",
    sinonimos: "overhead tricep extension,extensión triceps cabeza",
  },
  {
    nombre: "Sentadilla con barra",
    patron: "sentadilla",
    grupo: "Piernas",
    grupo2: "Glúteos,Core",
    nivel: "intermedio",
    tipo: "fuerza",
    modalidades: "fuerza,hipertrofia,potencia,crossfit",
    tecnica: "Barra en trapecios. Pies a anchura de hombros. Rodillas siguen la dirección de los pies. Baja hasta paralelo o más. Espalda neutra. Core activado todo el tiempo.",
    yt_id: "1oed-UmAxFs",
    sinonimos: "squat,sentadilla barra,back squat",
  },
  {
    nombre: "Sentadilla goblet",
    patron: "sentadilla",
    grupo: "Piernas",
    grupo2: "Glúteos,Core",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "fuerza,perdida_grasa,resistencia,wellness",
    tecnica: "Mancuerna o kettlebell al pecho. Pies ligeramente más anchos que hombros. Baja entre los pies. Ideal para aprender la sentadilla. Torso erguido.",
    yt_id: "MxsFDhcyFyE",
    sinonimos: "goblet squat,sentadilla copa,sentadilla mancuerna",
  },
  {
    nombre: "Prensa de pierna",
    patron: "sentadilla",
    grupo: "Piernas",
    grupo2: "Glúteos",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "fuerza,hipertrofia,perdida_grasa",
    tecnica: "Pies a anchura de hombros en la plataforma. Baja hasta 90 grados de rodilla. No bloquees las rodillas arriba. Posición de pies determina activación.",
    yt_id: "IZxyjW7MPJQ",
    sinonimos: "leg press,prensa pierna,plate loaded press",
  },
  {
    nombre: "Extensión de cuádriceps",
    patron: "aislamiento",
    grupo: "Piernas",
    grupo2: "",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "hipertrofia,perdida_grasa,rehabilitacion",
    tecnica: "Aislamiento del cuádriceps. Pausa de 1 segundo arriba. Baja con control. Posición del asiento afecta la activación. Ideal como trabajo complementario.",
    yt_id: "YyvSfVjQeL0",
    sinonimos: "leg extension,extensión cuádriceps,quad extension",
  },
  {
    nombre: "Zancadas",
    patron: "sentadilla",
    grupo: "Piernas",
    grupo2: "Glúteos",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "fuerza,perdida_grasa,resistencia,wellness",
    tecnica: "Paso largo hacia adelante. Rodilla trasera casi toca el suelo. Rodilla delantera no sobrepasa el pie. Torso erguido. Vuelve a la posición inicial empujando con el talón.",
    yt_id: "D7KaRcUTQeE",
    sinonimos: "lunges,zancadas mancuernas,lunge",
  },
  {
    nombre: "Sentadilla búlgara",
    patron: "sentadilla",
    grupo: "Piernas",
    grupo2: "Glúteos",
    nivel: "intermedio",
    tipo: "fuerza",
    modalidades: "fuerza,hipertrofia",
    tecnica: "Pie trasero elevado en banco. Baja hasta que la rodilla trasera casi toque el suelo. Gran activación del cuádriceps y glúteo. Mantén el torso erguido.",
    yt_id: "2C-uNgKwPLE",
    sinonimos: "bulgarian split squat,zancada búlgara,split squat",
  },
  {
    nombre: "Hack squat",
    patron: "sentadilla",
    grupo: "Piernas",
    grupo2: "Glúteos",
    nivel: "intermedio",
    tipo: "fuerza",
    modalidades: "fuerza,hipertrofia",
    tecnica: "Máquina o barra detrás. Pies adelantados. Énfasis en el cuádriceps. Rodillas siguen la dirección de los pies. Baja hasta paralelo.",
    yt_id: "EdtPMS_OoAc",
    sinonimos: "hack squat máquina,hack squat",
  },
  {
    nombre: "Peso muerto convencional",
    patron: "bisagra",
    grupo: "Posterior",
    grupo2: "Glúteos,Espalda",
    nivel: "intermedio",
    tipo: "fuerza",
    modalidades: "fuerza,potencia,hibrido",
    tecnica: "Barra sobre los pies. Agarre a anchura de hombros. Espalda neutra. Empuja el suelo más que tirar de la barra. Caderas y hombros suben a la vez. Lockout con glúteos apretados.",
    yt_id: "op9kVnSso6Q",
    sinonimos: "deadlift,peso muerto,conventional deadlift",
  },
  {
    nombre: "Peso muerto rumano",
    patron: "bisagra",
    grupo: "Posterior",
    grupo2: "Glúteos",
    nivel: "intermedio",
    tipo: "fuerza",
    modalidades: "fuerza,hipertrofia",
    tecnica: "Piernas casi rectas con rodillas ligeramente flexionadas. Bisagra de cadera. Baja la barra por las piernas. Siente el estiramiento en isquios. Vuelve con extensión de cadera.",
    yt_id: "JCXUYuzwNrM",
    sinonimos: "RDL,romanian deadlift,rumano",
  },
  {
    nombre: "Peso muerto sumo",
    patron: "bisagra",
    grupo: "Posterior",
    grupo2: "Glúteos,Aductores",
    nivel: "intermedio",
    tipo: "fuerza",
    modalidades: "fuerza,potencia",
    tecnica: "Pies muy abiertos, puntas hacia afuera. Agarre estrecho entre las piernas. Torso más vertical que el convencional. Mayor activación de aductores y glúteos.",
    yt_id: "oiDczs9j75E",
    sinonimos: "sumo deadlift,sumo",
  },
  {
    nombre: "Curl femoral tumbado",
    patron: "aislamiento",
    grupo: "Isquios",
    grupo2: "",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "hipertrofia,perdida_grasa",
    tecnica: "Tumbado boca abajo. Lleva los talones hacia los glúteos. Caderas pegadas al banco. Control en la bajada. Pausa de 1 segundo arriba.",
    yt_id: "1Tq3QdYUuHs",
    sinonimos: "leg curl,curl femoral,hamstring curl",
  },
  {
    nombre: "Good morning",
    patron: "bisagra",
    grupo: "Posterior",
    grupo2: "Glúteos",
    nivel: "avanzado",
    tipo: "fuerza",
    modalidades: "fuerza",
    tecnica: "Barra en trapecios. Bisagra de cadera con espalda neutra. Rodillas ligeramente flexionadas. Baja hasta que el torso esté casi paralelo. Excelente para isquios y espalda baja.",
    yt_id: "YA-h3n9L4YU",
    sinonimos: "good morning barra",
  },
  {
    nombre: "Hip thrust",
    patron: "hip_extension",
    grupo: "Glúteos",
    grupo2: "Isquios",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "fuerza,hipertrofia,perdida_grasa",
    tecnica: "Espalda apoyada en banco. Barra sobre las caderas con almohadilla. Empuja con los talones. Aprieta los glúteos arriba. Caderas completamente extendidas. Pausa de 1 segundo.",
    yt_id: "Zp26q4BY5HE",
    sinonimos: "hip thrust barra,glute bridge weighted,empuje cadera",
  },
  {
    nombre: "Puente de glúteos",
    patron: "hip_extension",
    grupo: "Glúteos",
    grupo2: "",
    nivel: "principiante",
    tipo: "peso_corporal",
    modalidades: "wellness,perdida_grasa,rehabilitacion",
    tecnica: "Tumbado boca arriba. Pies apoyados en el suelo. Sube las caderas apretando glúteos. Pausa de 2 segundos arriba. Versión sin peso del hip thrust.",
    yt_id: "OUgsJ8-Vi0E",
    sinonimos: "glute bridge,puente gluteo",
  },
  {
    nombre: "Patada de glúteo en polea",
    patron: "hip_extension",
    grupo: "Glúteos",
    grupo2: "",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "hipertrofia,perdida_grasa",
    tecnica: "De pie frente a la polea. Extiende la cadera hacia atrás. Mantén el torso estable. Aprieta el glúteo en la extensión. No balancees el cuerpo.",
    yt_id: "Ex2EhRy8sxE",
    sinonimos: "cable kickback,patada trasera polea",
  },
  {
    nombre: "Plancha frontal",
    patron: "core",
    grupo: "Core",
    grupo2: "",
    nivel: "principiante",
    tipo: "peso_corporal",
    modalidades: "wellness,resistencia,crossfit,calistenia",
    tecnica: "Cuerpo recto de cabeza a talones. Codos bajo los hombros. Activa el core sin aguantar la respiración. No dejes caer las caderas. Mira al suelo.",
    yt_id: "pSHjTRCQxIw",
    sinonimos: "plank,plancha abdominal,forearm plank",
  },
  {
    nombre: "Crunch abdominal",
    patron: "core",
    grupo: "Core",
    grupo2: "",
    nivel: "principiante",
    tipo: "peso_corporal",
    modalidades: "wellness,perdida_grasa",
    tecnica: "Manos detrás de la cabeza sin tirar del cuello. Sube solo los hombros del suelo. Exhala al subir. No completes el sit-up. Mantén el lumbar apoyado.",
    yt_id: "5ER5Of4MOPI",
    sinonimos: "crunch,abdominales,abdominal crunch",
  },
  {
    nombre: "Rueda abdominal",
    patron: "core",
    grupo: "Core",
    grupo2: "Hombros",
    nivel: "avanzado",
    tipo: "peso_corporal",
    modalidades: "calistenia,fuerza",
    tecnica: "Comienza de rodillas. Rueda hacia adelante manteniendo el core activado. Llega hasta donde puedas sin hundir la espalda. Vuelve contrayendo el core, no la espalda.",
    yt_id: "BNBdFGF6z4M",
    sinonimos: "ab wheel,wheel rollout,rueda ab",
  },
  {
    nombre: "Elevación de piernas colgado",
    patron: "core",
    grupo: "Core",
    grupo2: "Flexores cadera",
    nivel: "avanzado",
    tipo: "peso_corporal",
    modalidades: "calistenia,fuerza",
    tecnica: "Colgado de la barra. Eleva las piernas hasta la horizontal o más. Control total. Evita el balanceo. Versión avanzada: piernas rectas.",
    yt_id: "JB2oyawG9KQ",
    sinonimos: "hanging leg raise,elevacion piernas barra",
  },
  {
    nombre: "Rotación con cable",
    patron: "core",
    grupo: "Core",
    grupo2: "Oblicuos",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "fuerza,resistencia,wellness",
    tecnica: "Polea a altura del pecho. Gira el torso sin mover los pies. Brazos extendidos. Control total. Trabaja los oblicuos rotadores.",
    yt_id: "zBi7VDNDi3Q",
    sinonimos: "cable rotation,rotación torso,woodchop",
  },
  {
    nombre: "Burpees",
    patron: "core",
    grupo: "Full body",
    grupo2: "",
    nivel: "principiante",
    tipo: "cardio",
    modalidades: "crossfit,perdida_grasa,resistencia",
    tecnica: "De pie al suelo en plancha. Flexión. Salta los pies a las manos. Salto vertical con brazos arriba. Mantén el ritmo respiratorio. Modifica quitando la flexión si es necesario.",
    yt_id: "dZgVxmf6jkA",
    sinonimos: "burpee,burpees",
  },
  {
    nombre: "Kettlebell swing",
    patron: "bisagra",
    grupo: "Full body",
    grupo2: "Glúteos,Posterior",
    nivel: "intermedio",
    tipo: "fuerza",
    modalidades: "crossfit,hibrido,potencia,perdida_grasa",
    tecnica: "Bisagra de cadera explosiva. La kettlebell sube por la fuerza de las caderas, no de los brazos. Aprieta glúteos y core en la parte alta. Rodillas ligeramente flexionadas.",
    yt_id: "sSESeQAir2c",
    sinonimos: "swing kettlebell,kb swing",
  },
  {
    nombre: "Box jump",
    patron: "sentadilla",
    grupo: "Piernas",
    grupo2: "Full body",
    nivel: "intermedio",
    tipo: "cardio",
    modalidades: "crossfit,potencia,resistencia",
    tecnica: "Posición de semisentadilla. Salto explosivo al cajón. Amortiza la caída con las rodillas flexionadas. Baja del cajón con control. No saltes de vuelta.",
    yt_id: "52r_Ul5k03g",
    sinonimos: "salto al cajón,box jumps",
  },
  {
    nombre: "Mountain climbers",
    patron: "core",
    grupo: "Full body",
    grupo2: "Core",
    nivel: "principiante",
    tipo: "cardio",
    modalidades: "crossfit,perdida_grasa,resistencia",
    tecnica: "Posición de plancha. Alterna rodillas al pecho rápidamente. Core activado. No levantes las caderas. Mantén los hombros sobre las muñecas.",
    yt_id: "nmwgirgXLYM",
    sinonimos: "escaladores,mountain climber",
  },
  {
    nombre: "Saltos a la comba",
    patron: "cardio",
    grupo: "Full body",
    grupo2: "Piernas",
    nivel: "principiante",
    tipo: "cardio",
    modalidades: "resistencia,perdida_grasa,crossfit",
    tecnica: "Salto mínimo, justo para que pase la cuerda. Aterrizaje en la punta de los pies. Muñecas giran la cuerda, no los hombros. Mantén una cadencia constante.",
    yt_id: "FJmRQ5iTXKE",
    sinonimos: "jump rope,cuerda,saltar a la comba",
  },
  {
    nombre: "Sentadilla profunda con pausa",
    patron: "sentadilla",
    grupo: "Piernas",
    grupo2: "Core,Movilidad",
    nivel: "principiante",
    tipo: "movilidad",
    modalidades: "movilidad,wellness",
    tecnica: "Baja hasta el fondo y mantén 30-60 segundos. Talones en el suelo. Manos juntas para mantener el torso erguido. Excelente para movilidad de cadera y tobillo.",
    yt_id: "qHqiyXJBpzc",
    sinonimos: "deep squat hold,sentadilla profunda",
  },
  {
    nombre: "Rotación torácica en cuadrupedia",
    patron: "movilidad",
    grupo: "Espalda",
    grupo2: "Core",
    nivel: "principiante",
    tipo: "movilidad",
    modalidades: "movilidad,wellness,rehabilitacion",
    tecnica: "En cuadrupedia. Pon una mano detrás de la cabeza. Gira el codo hacia el techo. Sigue con la mirada. Fundamental para salud de la columna torácica.",
    yt_id: "9yHRMpvxz1c",
    sinonimos: "thoracic rotation,rotación torácica",
  },
  {
    nombre: "Hip flexor stretch",
    patron: "movilidad",
    grupo: "Cadera",
    grupo2: "",
    nivel: "principiante",
    tipo: "movilidad",
    modalidades: "movilidad,wellness",
    tecnica: "Rodilla en el suelo, otro pie adelante. Empuja la cadera hacia adelante. Mantén 30-60 segundos. Fundamental para quienes están sentados muchas horas.",
    yt_id: "YqF8BnMsNaI",
    sinonimos: "estiramiento flexor cadera,hip flexor",
  },
  {
    nombre: "Cargada de potencia",
    patron: "bisagra",
    grupo: "Full body",
    grupo2: "Piernas,Hombros",
    nivel: "avanzado",
    tipo: "fuerza",
    modalidades: "crossfit,potencia",
    tecnica: "Triple extensión de tobillo, rodilla y cadera. Encoge los hombros. Sube la barra pegada al cuerpo. Atrapa la barra en la posición de front squat. Requiere aprendizaje técnico.",
    yt_id: "EKRiW9Yt3ps",
    sinonimos: "power clean,clean,cargada",
  },
  {
    nombre: "Press banca agarre cerrado",
    patron: "empuje_horizontal",
    grupo: "Tríceps",
    grupo2: "Pecho",
    nivel: "intermedio",
    tipo: "fuerza",
    modalidades: "fuerza,hipertrofia",
    tecnica: "Agarre a anchura de hombros o más estrecho. Mayor activación del tríceps. Baja hasta el pecho. Codos más cerrados que en el press normal.",
    yt_id: "nEF0bv2FW90",
    sinonimos: "close grip bench,press agarre cerrado",
  },
  {
    nombre: "Remo en T",
    patron: "tiron_horizontal",
    grupo: "Espalda",
    grupo2: "Bíceps",
    nivel: "intermedio",
    tipo: "fuerza",
    modalidades: "fuerza,hipertrofia",
    tecnica: "Barra en esquina. Agarre a anchura de hombros. Lleva la barra al pecho. Aprieta escápulas. Torso inclinado 45 grados. Control total en la bajada.",
    yt_id: "j3Igk5NYpzM",
    sinonimos: "t-bar row,remo T,remo barra T",
  },
  {
    nombre: "Pullover con mancuerna",
    patron: "tiron_vertical",
    grupo: "Espalda",
    grupo2: "Pecho",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "hipertrofia",
    tecnica: "Tumbado transversal al banco. Mancuerna sobre el pecho. Baja hacia atrás y abajo. Siente el estiramiento del dorsal. Mantén los codos ligeramente flexionados.",
    yt_id: "FK4rHfGJ9bA",
    sinonimos: "dumbbell pullover,pullover",
  },
  {
    nombre: "Fondos en banco",
    patron: "empuje_vertical",
    grupo: "Tríceps",
    grupo2: "",
    nivel: "principiante",
    tipo: "peso_corporal",
    modalidades: "wellness,calistenia,perdida_grasa",
    tecnica: "Manos en el banco, pies al frente. Baja hasta que los codos queden a 90 grados. Cuerpo pegado al banco. Versión más fácil que los fondos en paralelas.",
    yt_id: "c3ZGl4pHAeE",
    sinonimos: "tricep dips bench,fondos banco tríceps",
  },
  {
    nombre: "Peso muerto con mancuernas",
    patron: "bisagra",
    grupo: "Posterior",
    grupo2: "Glúteos",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "fuerza,perdida_grasa,wellness",
    tecnica: "Ideal para principiantes o cuando no hay barra. Misma mecánica que el peso muerto convencional. Mancuernas a los lados del cuerpo o delante de las piernas.",
    yt_id: "r4MzxtBKyeE",
    sinonimos: "dumbbell deadlift,peso muerto mancuernas",
  },
  {
    nombre: "Step up al cajón",
    patron: "sentadilla",
    grupo: "Piernas",
    grupo2: "Glúteos",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "fuerza,perdida_grasa,wellness,resistencia",
    tecnica: "Sube al cajón empujando con el talón del pie adelantado. No uses el impulso del pie trasero. Baja con control. Altura del cajón determina la dificultad.",
    yt_id: "dQqApCGd5Ss",
    sinonimos: "step up,subida cajón",
  },
  {
    nombre: "Sentadilla en máquina Smith",
    patron: "sentadilla",
    grupo: "Piernas",
    grupo2: "Glúteos",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "hipertrofia,fuerza",
    tecnica: "La barra guiada permite enfocarse en la técnica. Pies ligeramente adelantados. Baja hasta paralelo. Menos activación de estabilizadores que la sentadilla libre.",
    yt_id: "FNNfHM0KKlE",
    sinonimos: "smith machine squat,sentadilla smith",
  },
  {
    nombre: "Abductores en máquina",
    patron: "aislamiento",
    grupo: "Piernas",
    grupo2: "Glúteos",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "hipertrofia,perdida_grasa,wellness",
    tecnica: "Apertura de piernas contra resistencia. Activa glúteo medio y tensor. Ideal combinado con el hip thrust. Pausa de 1 segundo al final.",
    yt_id: "IOqZP-Hc-DY",
    sinonimos: "hip abduction,abductores,abductor machine",
  },
  {
    nombre: "Aductores en máquina",
    patron: "aislamiento",
    grupo: "Piernas",
    grupo2: "",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "hipertrofia,perdida_grasa",
    tecnica: "Cierre de piernas contra resistencia. Activa los músculos aductores del muslo. Complementario al trabajo de glúteos y sentadilla.",
    yt_id: "CaEMG_oGBio",
    sinonimos: "hip adduction,aductores,adductor machine",
  },
  {
    nombre: "Plancha lateral",
    patron: "core",
    grupo: "Core",
    grupo2: "Oblicuos",
    nivel: "principiante",
    tipo: "peso_corporal",
    modalidades: "wellness,calistenia,resistencia",
    tecnica: "Apoyado en un codo. Cuerpo recto lateral. Cadera elevada. Activa los oblicuos. Versión fácil: rodillas apoyadas. Mantén 20-60 segundos.",
    yt_id: "_6vjo5V1EqM",
    sinonimos: "side plank,plancha lateral oblicuos",
  },
  {
    nombre: "Russian twist",
    patron: "core",
    grupo: "Core",
    grupo2: "Oblicuos",
    nivel: "principiante",
    tipo: "peso_corporal",
    modalidades: "perdida_grasa,resistencia,wellness",
    tecnica: "Sentado con torso inclinado 45 grados. Gira el torso de lado a lado. Con o sin peso. Mantén los pies elevados para mayor dificultad.",
    yt_id: "wkD8rjkodUI",
    sinonimos: "russian twists,rotación rusa",
  },
  {
    nombre: "Tijeras abdominales",
    patron: "core",
    grupo: "Core",
    grupo2: "Flexores cadera",
    nivel: "principiante",
    tipo: "peso_corporal",
    modalidades: "perdida_grasa,wellness",
    tecnica: "Tumbado. Piernas elevadas y alternando arriba y abajo. Lumbar pegado al suelo. Core activado durante todo el movimiento.",
    yt_id: "ZB1SwBRVLCc",
    sinonimos: "scissors,flutter kicks,patadas tijera",
  },
  {
    nombre: "Press Arnold",
    patron: "empuje_vertical",
    grupo: "Hombros",
    grupo2: "Tríceps",
    nivel: "intermedio",
    tipo: "fuerza",
    modalidades: "hipertrofia",
    tecnica: "Comienza con las palmas hacia ti. Gira las palmas al frente mientras subes. Mayor rango de movimiento que el press normal. Mayor activación del deltoides anterior y medio.",
    yt_id: "3ml7BH7mNwQ",
    sinonimos: "arnold press,press arnold mancuernas",
  },
  {
    nombre: "Sentadilla frontal",
    patron: "sentadilla",
    grupo: "Piernas",
    grupo2: "Core",
    nivel: "avanzado",
    tipo: "fuerza",
    modalidades: "fuerza,crossfit,potencia",
    tecnica: "Barra en la parte delantera de los hombros. Mayor demanda de movilidad. Torso más vertical. Mayor activación del cuádriceps. Requiere buena movilidad de muñeca.",
    yt_id: "m4ytaCJZDoE",
    sinonimos: "front squat,sentadilla frontal barra",
  },
  {
    nombre: "Clean and press",
    patron: "bisagra",
    grupo: "Full body",
    grupo2: "Hombros,Piernas",
    nivel: "avanzado",
    tipo: "fuerza",
    modalidades: "crossfit,potencia,hibrido",
    tecnica: "Combinación de cargada y press. Requiere técnica en ambos movimientos. Alta demanda neuromuscular. Excelente para potencia y coordinación.",
    yt_id: "YNn7FfCTuC4",
    sinonimos: "thruster,clean press",
  },
  {
    nombre: "Jalón con agarre supino",
    patron: "tiron_vertical",
    grupo: "Espalda",
    grupo2: "Bíceps",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "hipertrofia,fuerza",
    tecnica: "Agarre supino más estrecho que el hombro. Mayor activación del bíceps. Lleva la barra al pecho. Aprieta el dorsal al final.",
    yt_id: "sZVCfNmhGg8",
    sinonimos: "underhand lat pulldown,jalón supino,reverse grip pulldown",
  },
  {
    nombre: "Fondos entre bancos",
    patron: "empuje_horizontal",
    grupo: "Tríceps",
    grupo2: "Pecho",
    nivel: "principiante",
    tipo: "peso_corporal",
    modalidades: "calistenia,wellness",
    tecnica: "Dos bancos paralelos. Pies en un banco, manos en el otro. Baja hasta 90 grados de codo. Peso adicional en el regazo para mayor dificultad.",
    yt_id: "jox1rb5krQI",
    sinonimos: "bench dips,fondos entre sillas",
  },
  {
    nombre: "Curl en banco inclinado",
    patron: "aislamiento",
    grupo: "Bíceps",
    grupo2: "",
    nivel: "intermedio",
    tipo: "fuerza",
    modalidades: "hipertrofia",
    tecnica: "Banco a 45-60 grados. Mayor estiramiento del bíceps. Brazos colgando. Sube sin mover los codos. Excelente para la cabeza larga del bíceps.",
    yt_id: "lMNGKwmCHbc",
    sinonimos: "incline curl,curl inclinado biceps",
  },
  {
    nombre: "Abdominal en rueda",
    patron: "core",
    grupo: "Core",
    grupo2: "Hombros",
    nivel: "avanzado",
    tipo: "peso_corporal",
    modalidades: "calistenia",
    tecnica: "De rodillas o de pie. Rueda hacia adelante manteniendo la espalda neutra. Vuelve contrayendo el core activamente. No arquees la zona lumbar.",
    yt_id: "BNBdFGF6z4M",
    sinonimos: "ab rollout,rueda abdominal",
  },
  {
    nombre: "Estocada inversa",
    patron: "sentadilla",
    grupo: "Piernas",
    grupo2: "Glúteos",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "fuerza,perdida_grasa,wellness",
    tecnica: "Paso hacia atrás en lugar de adelante. Menor tensión en la rodilla delantera. Rodilla trasera casi toca el suelo. Empuja con el pie delantero para volver.",
    yt_id: "xrjMX21iBe4",
    sinonimos: "reverse lunge,estocada hacia atrás,lunge inverso",
  },
  {
    nombre: "Remo en máquina",
    patron: "tiron_horizontal",
    grupo: "Espalda",
    grupo2: "Bíceps",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "fuerza,hipertrofia,perdida_grasa",
    tecnica: "Pecho apoyado en el soporte. Lleva los mangos hasta el abdomen. Aprieta las escápulas. Ideal para principiantes por la guía del movimiento.",
    yt_id: "xQNrFHEMhI4",
    sinonimos: "chest supported row,remo pecho apoyado",
  },
  {
    nombre: "Extensión de espalda",
    patron: "bisagra",
    grupo: "Espalda",
    grupo2: "Glúteos",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "fuerza,wellness,rehabilitacion",
    tecnica: "En banco romano o hiperextensiones. Baja el torso y sube hasta la posición neutra. No hiperextiendas la columna. Glúteos apretados arriba.",
    yt_id: "ph3pMgIEMzE",
    sinonimos: "hyperextension,hiperextensión,back extension",
  },
  {
    nombre: "Sentadilla en caja",
    patron: "sentadilla",
    grupo: "Piernas",
    grupo2: "Glúteos",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "fuerza,wellness,rehabilitacion",
    tecnica: "Caja detrás para marcar la profundidad. Siéntate en la caja brevemente. Mantén el peso en los talones. Ideal para aprender la sentadilla o en rehabilitación.",
    yt_id: "yMzAFd99XNQ",
    sinonimos: "box squat,sentadilla cajón",
  },
  {
    nombre: "Curl femoral de pie",
    patron: "aislamiento",
    grupo: "Isquios",
    grupo2: "",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "hipertrofia",
    tecnica: "De pie en la máquina. Lleva el talón hacia el glúteo. Controla la bajada. Cadera ligeramente flexionada para mayor rango.",
    yt_id: "vYvH-mLHqQ4",
    sinonimos: "standing leg curl,curl femoral pie",
  },
  {
    nombre: "Sentadilla pistola",
    patron: "sentadilla",
    grupo: "Piernas",
    grupo2: "Core",
    nivel: "avanzado",
    tipo: "peso_corporal",
    modalidades: "calistenia,potencia",
    tecnica: "Sentadilla a una pierna. Pierna libre extendida al frente. Requiere gran movilidad y fuerza unilateral. Progression: sentadilla en caja a una pierna.",
    yt_id: "vq5-vdgJc0I",
    sinonimos: "pistol squat,sentadilla una pierna",
  },
  {
    nombre: "Nordic curl",
    patron: "bisagra",
    grupo: "Isquios",
    grupo2: "",
    nivel: "avanzado",
    tipo: "peso_corporal",
    modalidades: "fuerza,calistenia",
    tecnica: "Rodillas en el suelo, pies sujetos. Baja el torso hacia el suelo controlando con los isquios. Vuelve con los brazos si es necesario. Altísima activación de isquiotibiales.",
    yt_id: "2GqpIPuEBqM",
    sinonimos: "nordic hamstring curl,curl nórdico",
  },
  {
    nombre: "Dips en anillas",
    patron: "empuje_vertical",
    grupo: "Pecho",
    grupo2: "Tríceps",
    nivel: "avanzado",
    tipo: "peso_corporal",
    modalidades: "calistenia",
    tecnica: "Mayor inestabilidad que las paralelas. Mayor rango de movimiento. Aprieta las anillas hacia el cuerpo. Baja hasta 90 grados de codo o más.",
    yt_id: "AHLnNQPSlAM",
    sinonimos: "ring dips,fondos en anillas",
  },
  {
    nombre: "Remo en anillas",
    patron: "tiron_horizontal",
    grupo: "Espalda",
    grupo2: "Bíceps",
    nivel: "intermedio",
    tipo: "peso_corporal",
    modalidades: "calistenia",
    tecnica: "Debajo de las anillas. Tira hacia el pecho. Mayor libertad de movimiento que la barra fija. Cuanto más horizontal el cuerpo, más difícil.",
    yt_id: "LY4x4VQyNnM",
    sinonimos: "ring row,remo anillas",
  },
  {
    nombre: "Farmer's carry",
    patron: "core",
    grupo: "Full body",
    grupo2: "Core,Antebrazos",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "fuerza,crossfit,potencia",
    tecnica: "Camina con pesas pesadas en cada mano. Core activado. Espalda erguida. Hombros hacia atrás y abajo. Excelente para grip y estabilidad de core.",
    yt_id: "Fkzk0icCkM4",
    sinonimos: "farmer walk,caminata con pesas",
  },
  {
    nombre: "Turkish get up",
    patron: "core",
    grupo: "Full body",
    grupo2: "Hombros,Core",
    nivel: "avanzado",
    tipo: "fuerza",
    modalidades: "crossfit,movilidad,fuerza",
    tecnica: "De tumbado a de pie con kettlebell sobre la cabeza. Movimiento por fases. Brazo vertical durante todo el movimiento. Exige movilidad, fuerza y coordinación.",
    yt_id: "44ScXWFaVBs",
    sinonimos: "TGU,turkish getup",
  },
  {
    nombre: "Sentadilla overhead",
    patron: "sentadilla",
    grupo: "Full body",
    grupo2: "Hombros,Core",
    nivel: "avanzado",
    tipo: "fuerza",
    modalidades: "crossfit,potencia",
    tecnica: "Barra sobre la cabeza durante la sentadilla. Agarre muy abierto. Brazos completamente extendidos. Exige gran movilidad de hombros y tobillo.",
    yt_id: "RD_vUnqwqqI",
    sinonimos: "overhead squat,OHS",
  },
  {
    nombre: "Muscle up",
    patron: "tiron_vertical",
    grupo: "Full body",
    grupo2: "Espalda,Pecho",
    nivel: "avanzado",
    tipo: "peso_corporal",
    modalidades: "calistenia",
    tecnica: "Transición explosiva entre dominada y fondo. Requiere dominadas explosivas y técnica de transición. Uno de los movimientos más completos de la calistenia.",
    yt_id: "pX4fNISS5BM",
    sinonimos: "muscle-up,muscle up barra",
  },
  {
    nombre: "Handstand push up",
    patron: "empuje_vertical",
    grupo: "Hombros",
    grupo2: "Tríceps,Core",
    nivel: "avanzado",
    tipo: "peso_corporal",
    modalidades: "calistenia",
    tecnica: "Vertical apoyado en la pared. Baja la cabeza hacia el suelo. Empuja hasta extender los codos. Requiere gran fuerza de hombros y control del core.",
    yt_id: "3sT7Jc7TNhA",
    sinonimos: "HSPU,flexiones verticales,handstand press",
  },
  {
    nombre: "Paseos del granjero en punta de pies",
    patron: "cardio",
    grupo: "Piernas",
    grupo2: "Core",
    nivel: "principiante",
    tipo: "movilidad",
    modalidades: "wellness,movilidad",
    tecnica: "Camina en la punta de los pies con pesas. Activa la pantorrilla y mejora el equilibrio. Core activado. Pasos cortos y controlados.",
    yt_id: "Fkzk0icCkM4",
    sinonimos: "tiptoe farmer walk,caminata puntillas",
  },
  {
    nombre: "Elevación de talones de pie",
    patron: "aislamiento",
    grupo: "Piernas",
    grupo2: "Pantorrilla",
    nivel: "principiante",
    tipo: "fuerza",
    modalidades: "hipertrofia,wellness",
    tecnica: "De pie. Sube en la punta de los pies. Pausa de 1 segundo arriba. Baja completamente para el estiramiento. Con peso adicional para mayor dificultad.",
    yt_id: "JbyjNymZOt0",
    sinonimos: "calf raise,elevación pantorrilla,standing calf raise",
  },
]
